apiVersion: v1
kind: Service
metadata:
  name: harnessbank-demo-end2end
  namespace: harnessbank-demo-end2end
  labels:
    app: harnessbank-demo-end2end
spec:
  type: LoadBalancer
  selector:
    app: harnessbank-demo-end2end
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
